main:
  ind: true
  debug_bijection: false
  compute_metrics: false
  compute_goals: true
  plot: true

goal_detection:
  samples_frequency: 10
  resample_frequency: 25
  plot_rollout: true
  try_count: 2
  threshold: 1.5
  goals: [[ 17.40, -4.97 ], [ 75.18, -56.65 ], [ 62.47, -17.54 ]]

model:
  directory: '/home/balint/Documents/precog/output/esp_train_results/2021-01/01-31-16-01-10_ind_heckstrasse_precog.bijection.social_convrnn.SocialConvRNN_'

hardware:
  allow_growth: true
  per_process_gpu_memory_fraction: 1.0
      
hydra:
  job_logging:
    handlers:
      console:
        level: INFO
      file:
        level: DEBUG
  run:
    dir: /home/balint/Documents/precog/output/esp_infer_results/${now:%Y-%m}/${now:%m-%d-%H-%M-%S}_${dataset.class}

images:
  ext: 'jpg'
  figsize: [20, 20]

split: 'test'

dataset:
  plot_allchannel: false

plotting:
  bev_kwargs:
    onechannel: False
    allchannel: False

defaults:
  - dataset: ind_heckstrasse
