main:
  seed: 42
  eager: false
  tag: ""

hydra:
  job_logging:
    root:
       level: INFO
    handlers:
      console:
        level: INFO
      file:
        level: DEBUG
  run:
     dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}_${dataset.class}_${bijection.class}

distribution:
  params:
    K: 12
    sample_K: 12

bijection:
  params:
    A: 5

dataset:
  plot_allchannel: false

defaults:
  - hardware: shared_gpu  
  - optimizer: sgd_optimizer
  - dataset: ind_heckstrasse
  - bijection: social_convrnn
  - distribution: bijective_distribution
  - objective: forward_kl
  - sample_metric: mhat
  - proxy: empty_proxy
